tab = int(input('digite um numero pra ver sua tabuada: '))
print('----------------')
print('{} X {} = {}'.format(tab, 1, tab*1))
print('{} X {} = {}'.format(tab, 2, tab*2))
print('{} X {} = {}'.format(tab, 3, tab*3))
print('{} X {} = {}'.format(tab, 4, tab*4))
print('{} X {} = {}'.format(tab, 5, tab*5))
print('{} X {} = {}'.format(tab, 6, tab*6))
print('{} X {} = {}'.format(tab, 7, tab*7))
print('{} X {} = {}'.format(tab, 8, tab*8))
print('{} X {} = {}'.format(tab, 9, tab*9))
print('{} X {} = {}'.format(tab, 10, tab*10))
print('---------------')

